/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaveApprovalcopyRouteImport } from './routes/leave-approval copy'
import { Route as LeaveApprovalRouteImport } from './routes/leave-approval'
import { Route as CanvasRouteRouteImport } from './routes/canvas.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEmployeesRouteImport } from './routes/api/employees'
import { Route as ApiDepartmentsRouteImport } from './routes/api/departments'
import { Route as ApiDepartmentRelationshipsRouteImport } from './routes/api/department-relationships'
import { Route as ApiEmployeesIdRouteImport } from './routes/api/employees.$id'
import { Route as ApiDepartmentsIdRouteImport } from './routes/api/departments.$id'

const LeaveApprovalcopyRoute = LeaveApprovalcopyRouteImport.update({
  id: '/leave-approval copy',
  path: '/leave-approval copy',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveApprovalRoute = LeaveApprovalRouteImport.update({
  id: '/leave-approval',
  path: '/leave-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRouteRoute = CanvasRouteRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeesRoute = ApiEmployeesRouteImport.update({
  id: '/api/employees',
  path: '/api/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDepartmentsRoute = ApiDepartmentsRouteImport.update({
  id: '/api/departments',
  path: '/api/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDepartmentRelationshipsRoute =
  ApiDepartmentRelationshipsRouteImport.update({
    id: '/api/department-relationships',
    path: '/api/department-relationships',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEmployeesIdRoute = ApiEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEmployeesRoute,
} as any)
const ApiDepartmentsIdRoute = ApiDepartmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDepartmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRouteRoute
  '/leave-approval': typeof LeaveApprovalRoute
  '/leave-approval copy': typeof LeaveApprovalcopyRoute
  '/api/department-relationships': typeof ApiDepartmentRelationshipsRoute
  '/api/departments': typeof ApiDepartmentsRouteWithChildren
  '/api/employees': typeof ApiEmployeesRouteWithChildren
  '/api/departments/$id': typeof ApiDepartmentsIdRoute
  '/api/employees/$id': typeof ApiEmployeesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRouteRoute
  '/leave-approval': typeof LeaveApprovalRoute
  '/leave-approval copy': typeof LeaveApprovalcopyRoute
  '/api/department-relationships': typeof ApiDepartmentRelationshipsRoute
  '/api/departments': typeof ApiDepartmentsRouteWithChildren
  '/api/employees': typeof ApiEmployeesRouteWithChildren
  '/api/departments/$id': typeof ApiDepartmentsIdRoute
  '/api/employees/$id': typeof ApiEmployeesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRouteRoute
  '/leave-approval': typeof LeaveApprovalRoute
  '/leave-approval copy': typeof LeaveApprovalcopyRoute
  '/api/department-relationships': typeof ApiDepartmentRelationshipsRoute
  '/api/departments': typeof ApiDepartmentsRouteWithChildren
  '/api/employees': typeof ApiEmployeesRouteWithChildren
  '/api/departments/$id': typeof ApiDepartmentsIdRoute
  '/api/employees/$id': typeof ApiEmployeesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canvas'
    | '/leave-approval'
    | '/leave-approval copy'
    | '/api/department-relationships'
    | '/api/departments'
    | '/api/employees'
    | '/api/departments/$id'
    | '/api/employees/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canvas'
    | '/leave-approval'
    | '/leave-approval copy'
    | '/api/department-relationships'
    | '/api/departments'
    | '/api/employees'
    | '/api/departments/$id'
    | '/api/employees/$id'
  id:
    | '__root__'
    | '/'
    | '/canvas'
    | '/leave-approval'
    | '/leave-approval copy'
    | '/api/department-relationships'
    | '/api/departments'
    | '/api/employees'
    | '/api/departments/$id'
    | '/api/employees/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanvasRouteRoute: typeof CanvasRouteRoute
  LeaveApprovalRoute: typeof LeaveApprovalRoute
  LeaveApprovalcopyRoute: typeof LeaveApprovalcopyRoute
  ApiDepartmentRelationshipsRoute: typeof ApiDepartmentRelationshipsRoute
  ApiDepartmentsRoute: typeof ApiDepartmentsRouteWithChildren
  ApiEmployeesRoute: typeof ApiEmployeesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leave-approval copy': {
      id: '/leave-approval copy'
      path: '/leave-approval copy'
      fullPath: '/leave-approval copy'
      preLoaderRoute: typeof LeaveApprovalcopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave-approval': {
      id: '/leave-approval'
      path: '/leave-approval'
      fullPath: '/leave-approval'
      preLoaderRoute: typeof LeaveApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employees': {
      id: '/api/employees'
      path: '/api/employees'
      fullPath: '/api/employees'
      preLoaderRoute: typeof ApiEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/departments': {
      id: '/api/departments'
      path: '/api/departments'
      fullPath: '/api/departments'
      preLoaderRoute: typeof ApiDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/department-relationships': {
      id: '/api/department-relationships'
      path: '/api/department-relationships'
      fullPath: '/api/department-relationships'
      preLoaderRoute: typeof ApiDepartmentRelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employees/$id': {
      id: '/api/employees/$id'
      path: '/$id'
      fullPath: '/api/employees/$id'
      preLoaderRoute: typeof ApiEmployeesIdRouteImport
      parentRoute: typeof ApiEmployeesRoute
    }
    '/api/departments/$id': {
      id: '/api/departments/$id'
      path: '/$id'
      fullPath: '/api/departments/$id'
      preLoaderRoute: typeof ApiDepartmentsIdRouteImport
      parentRoute: typeof ApiDepartmentsRoute
    }
  }
}

interface ApiDepartmentsRouteChildren {
  ApiDepartmentsIdRoute: typeof ApiDepartmentsIdRoute
}

const ApiDepartmentsRouteChildren: ApiDepartmentsRouteChildren = {
  ApiDepartmentsIdRoute: ApiDepartmentsIdRoute,
}

const ApiDepartmentsRouteWithChildren = ApiDepartmentsRoute._addFileChildren(
  ApiDepartmentsRouteChildren,
)

interface ApiEmployeesRouteChildren {
  ApiEmployeesIdRoute: typeof ApiEmployeesIdRoute
}

const ApiEmployeesRouteChildren: ApiEmployeesRouteChildren = {
  ApiEmployeesIdRoute: ApiEmployeesIdRoute,
}

const ApiEmployeesRouteWithChildren = ApiEmployeesRoute._addFileChildren(
  ApiEmployeesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanvasRouteRoute: CanvasRouteRoute,
  LeaveApprovalRoute: LeaveApprovalRoute,
  LeaveApprovalcopyRoute: LeaveApprovalcopyRoute,
  ApiDepartmentRelationshipsRoute: ApiDepartmentRelationshipsRoute,
  ApiDepartmentsRoute: ApiDepartmentsRouteWithChildren,
  ApiEmployeesRoute: ApiEmployeesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
